name: Compile PHP
on:
    push:
        tags:
            - '*'

jobs:
    linux-x86_64-build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Call the build-docker.sh script
              run: ./build-docker.sh
              env:
                PHP_VERSION: ${{ github.ref_name}}
            - name: Upload to the tag
              uses: actions/upload-artifact@v4
              with:
                name: php-linux-x86_64
                path: php

    macos-x86_64-build:
        runs-on: macos-13
        steps:
            - uses: actions/checkout@v4
            - name: Install build dependencies from brew
              run: brew install autoconf automake libtool
            - name: Call the build-native.sh script
              run: ./build-native.sh
              env:
                PHP_VERSION: ${{ github.ref_name}}
            - name: Upload to the tag
              uses: actions/upload-artifact@v4
              with:
                name: php-macos-x86_64
                path: php

    macos-arm64-build:
        runs-on: macos-14
        steps:
            - uses: actions/checkout@v4
            - name: Install build dependencies from brew
              run: brew install autoconf automake libtool
            - name: Call the build-native.sh script
              run: ./build-native.sh
              env:
                PHP_VERSION: ${{ github.ref_name}}
            - name: Upload to the tag
              uses: actions/upload-artifact@v4
              with:
                name: php-macos-arm64
                path: php

    windows-x86_64-build:
        runs-on: windows-2022
        steps:
            - uses: actions/checkout@v4
            - uses: ilammy/msvc-dev-cmd@v1.4.1
            - name: Call the build-native.bat script
              run: ./build-native.bat
              env:
                PHP_VERSION: ${{ github.ref_name}}
            - name: Upload to the tag
              uses: actions/upload-artifact@v4
              with:
                name: php-windows-x86_64
                path: C:\php-sdk\php-src\x64\Release_TS\php.exe
